// client/src/pages/Social.vue
<template>
  <div class="min-h-screen bg-amber-50/50">
    <div class="container mx-auto px-4 py-8">
      <div class="space-y-8">
        <ScrollArea class="h-[calc(100vh-6rem)] rounded-lg p-4">
          <div class="space-y-6">
            <Card v-for="platform in socialPosts" :key="platform.platform" class="western-card">
              <CardContent class="p-6 space-y-4">
                <div class="flex items-center gap-2">
                  <component :is="platformIcon[platform.icon]" class="h-6 w-6 text-amber-800" />
                  <Badge class="bg-amber-800 text-amber-50">
                    {{ platform.platform }}
                  </Badge>
                </div>

                <div class="space-y-4">
                  <div
                    v-for="(post, index) in platform.posts"
                    :key="index"
                    class="border-l-2 border-amber-200 pl-4 space-y-2"
                  >
                    <div class="flex justify-between items-center">
                      <p class="font-semibold text-amber-900">{{ post.author }}</p>
                      <Badge variant="outline" class="text-amber-800">
                        {{ post.category }}
                      </Badge>
                    </div>
                    <p class="text-amber-800">{{ post.content }}</p>
                    <div class="flex gap-4 text-sm text-amber-700">
                      <span class="flex items-center gap-1">
                        {{ platform.platform === "Reddit" ? "⬆️" : "❤️" }}
                        {{ getLikes(post, platform.platform) }}
                      </span>
                      <span>📅 {{ post.date }}</span>
                      <span v-if="getSubreddit(post)">
                        📍 {{ getSubreddit(post) }}
                      </span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </ScrollArea>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { SiX, SiReddit, SiInstagram, SiLinkedin } from 'react-icons/si'
import { socialPosts, type SocialPost } from '@/data/social'

const platformIcon = {
  SiX,
  SiReddit,
  SiInstagram,
  SiLinkedin
}

const getLikes = (post: SocialPost, platform: string) => {
  if (platform === "Reddit" && "upvotes" in post) {
    return post.upvotes
  }
  if (platform === "LinkedIn" && "reactions" in post) {
    return post.reactions
  }
  if ("likes" in post) {
    return post.likes
  }
  return ""
}

const getSubreddit = (post: SocialPost): string | undefined => {
  if ("subreddit" in post) {
    return post.subreddit
  }
  return undefined
}
</script>

// client/src/pages/Social.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  SiX,
  SiReddit, 
  SiInstagram, 
  SiLinkedin 
} from "react-icons/si";
import { socialPosts, type SocialPost } from "@/data/social";

const getLikes = (post: SocialPost, platform: string) => {
  if (platform === "Reddit" && "upvotes" in post) {
    return post.upvotes;
  }
  if (platform === "LinkedIn" && "reactions" in post) {
    return post.reactions;
  }
  if ("likes" in post) {
    return post.likes;
  }
  return "";
};

const getSubreddit = (post: SocialPost): string | undefined => {
  if ("subreddit" in post) {
    return post.subreddit;
  }
  return undefined;
};

export default function Social() {
  return (
    <div className="min-h-screen bg-amber-50/50">
      <div className="container mx-auto px-4 py-8">
        <div className="space-y-8">
          <ScrollArea className="h-[calc(100vh-6rem)] rounded-lg p-4">
            <div className="space-y-6">
              {socialPosts.map((platform) => (
                <Card key={platform.platform} className="western-card">
                  <CardContent className="p-6 space-y-4">
                    <div className="flex items-center gap-2">
                      {platform.icon === "SiX" && <SiX className="h-6 w-6 text-amber-800" />}
                      {platform.icon === "SiReddit" && <SiReddit className="h-6 w-6 text-amber-800" />}
                      {platform.icon === "SiInstagram" && <SiInstagram className="h-6 w-6 text-amber-800" />}
                      {platform.icon === "SiLinkedin" && <SiLinkedin className="h-6 w-6 text-amber-800" />}
                      <Badge className="bg-amber-800 text-amber-50">
                        {platform.platform}
                      </Badge>
                    </div>

                    <div className="space-y-4">
                      {platform.posts.map((post, index) => (
                        <div key={index} className="border-l-2 border-amber-200 pl-4 space-y-2">
                          <div className="flex justify-between items-center">
                            <p className="font-semibold text-amber-900">{post.author}</p>
                            <Badge variant="outline" className="text-amber-800">
                              {post.category}
                            </Badge>
                          </div>
                          <p className="text-amber-800">{post.content}</p>
                          <div className="flex gap-4 text-sm text-amber-700">
                            <span className="flex items-center gap-1">
                              {platform.platform === "Reddit" ? "⬆️" : "❤️"}
                              {getLikes(post, platform.platform)}
                            </span>
                            <span>📅 {post.date}</span>
                            {getSubreddit(post) && (
                              <span>📍 {getSubreddit(post)}</span>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  );
}
